"""Guards the committed Dulles Toll Road route+price map.

Unlike oracles/i66.json/i95.json, there's no live feed to refresh against --
oracles/dulles_toll_road.json is generated by scripts/build_dulles_oracle.py
from a hand-transcribed rate table (that script's docstring records sources
and documented assumptions). These checks guard internal consistency: every
pair references a real node, every price is a well-formed decimal string,
and the well-known $6.00 mainline-plus-one-ramp trip total still holds --
not correctness against MWAA's actual current rates, which no test here can
verify automatically.

No network, no RDS.
"""

import json
from decimal import Decimal

from conftest import REPO_ROOT

ORACLE = json.loads((REPO_ROOT / "oracles" / "dulles_toll_road.json").read_text())
NODES: dict = ORACLE["nodes"]
PAIRS: list = ORACLE["pairs"]


def test_shape():
    assert set(ORACLE) == {"source_url", "retrieved_at", "notes", "nodes", "pairs"}
    for pair in PAIRS:
        assert set(pair) == {
            "direction",
            "entry",
            "exit",
            "price_peak_usd",
            "price_off_peak_usd",
        }


def test_pairs_are_well_formed():
    for p in PAIRS:
        assert p["entry"] in NODES and p["exit"] in NODES, p
        assert p["direction"] in ("EB", "WB"), p
        assert p["entry"] != p["exit"], p
        assert Decimal(p["price_peak_usd"]) >= 0, p


def test_no_time_of_day_variation():
    # Confirmed: the Dulles Toll Road has no peak/off-peak pricing, unlike
    # the Dulles Greenway -- both price fields must always match here.
    for p in PAIRS:
        assert p["price_peak_usd"] == p["price_off_peak_usd"], p


def test_boundary_node_exists_for_the_greenway_connection():
    assert any(
        n["label"] == "Route 28 (Dulles Toll Road / Dulles Greenway)"
        for n in NODES.values()
    )


def test_well_corroborated_mainline_plus_ramp_trip_totals_six_dollars():
    # A trip from a west-of-mainline ramp to the east end (Beltway) crosses
    # exactly one ramp toll ($2.00) plus the mainline toll ($4.00) -- the one
    # figure two independent sources agreed on during research.
    [reston_to_beltway] = [
        p
        for p in PAIRS
        if p["entry"] == "12" and p["exit"] == "1819" and p["direction"] == "EB"
    ]
    assert reston_to_beltway["price_peak_usd"] == "6.00"


def test_exit_16_ramp_toll_is_eastbound_only():
    [eb] = [
        p
        for p in PAIRS
        if p["entry"] == "13" and p["exit"] == "16" and p["direction"] == "EB"
    ]
    [wb] = [
        p
        for p in PAIRS
        if p["entry"] == "16" and p["exit"] == "13" and p["direction"] == "WB"
    ]
    # EB pays the Exit 16 ramp toll on top of the mainline crossing; WB does
    # not -- both cross the same mainline plaza, so the $2.00 gap is exactly
    # the documented eastbound-only ramp toll.
    assert Decimal(eb["price_peak_usd"]) - Decimal(wb["price_peak_usd"]) == Decimal(
        "2.00"
    )
