-- graph schema version: 1.0.0
--
-- Mirrors docs/toll-graph-spec.md. Keep in sync; the graph schema version
-- below must match the spec and is enforced by tests/test_graph.py.
--
-- Curated NOVA toll graph: i95_express + i495_express dynamic edges (317
-- OD pairs from the I-95/395/495 Express Lanes feed), i66_itb dynamic
-- edges (20 zone pairs from the I-66 ITB feed), and free junction
-- connector edges (feed IS NULL) at Springfield and the Beltway/66
-- interchange. Topology is static seed data; rebuild is the migration
-- strategy -- this file is idempotent (safe to re-run).

BEGIN;

DROP TABLE IF EXISTS graph_edge, graph_node;

CREATE TABLE graph_node (
    node_id  text PRIMARY KEY,   -- stable slug: 'i95x:garrisonville', 'i66:fairfax-dr'
    name     text NOT NULL,      -- canonical display name (hand-curated)
    corridor text NOT NULL CHECK (corridor IN ('i95_express','i495_express','i66_itb'))
);

CREATE TABLE graph_edge (
    from_node     text NOT NULL REFERENCES graph_node,
    to_node       text NOT NULL REFERENCES graph_node,
    feed          text CHECK (feed IN ('i95','i66')),   -- NULL = free junction connector
    od_pair_id    int,                                   -- i95 price key
    start_zone_id int, end_zone_id int                   -- i66 price key
);

-- Nodes (60): i95_express (34), i495_express (18), i66_itb (8).
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:alban', 'Alban', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:cardinal', 'Cardinal', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:dale-blvd', 'Dale Blvd', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:dc-pentagon-washington-blvd', 'DC/Pentagon/Washington Blvd', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:dumfries', 'Dumfries Rd (234)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:fairfax-county-pkwy', 'Fairfax County Pkwy (286)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:franconia-rd', 'Franconia Rd (644)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:franconia-springfield-pkwy', 'Franconia-Springfield Pkwy (289)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:garrisonville', 'Garrisonville Rd (610)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:gordon-blvd', 'Gordon Blvd (123)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:i395-95', 'I-395/95', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:i395-n', 'I-395 N', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:i495-springfield', 'I-495 (Springfield)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:i95-s-ft-belvoir', 'I-95 S / Ft Belvoir', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:i95-s-near-backlick-rd', 'I-95 S near Backlick Rd', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:i95-s-near-dale-blvd', 'I-95 S near Dale Blvd', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:joplin-rd', 'Joplin Rd (619)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:lorton', 'Lorton', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:newington', 'Newington', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:old-courthouse-rd', 'Old Courthouse Rd', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:opitz', 'Opitz', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:pentagon', 'Pentagon', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:prince-william-pkwy', 'Prince William Pkwy (294)', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:quantico', 'Quantico', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:rt17-95-nb', 'Rt 17 / 95 NB', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:rt17-95-sb', 'Rt 17 / 95 SB', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:russell-rd', 'Russell Rd', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:seminary-rd', 'Seminary Rd', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:shirlington-circle', 'Shirlington Circle', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:telegraph-rd', 'Telegraph Rd', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:turkeycock', 'Turkeycock', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:us-1', 'US 1', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:washington-blvd-pentagon', 'Washington Blvd / Pentagon', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i95x:washington-dc', 'Washington DC', 'i95_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:braddock', 'Braddock Rd', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:gallows', 'Gallows Rd', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:i395-495-hov', 'I-395-495 HOV', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:i395-95-495', 'I-395-95-495', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:i395-95-hov', 'I-395-95 HOV', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:i495-hov', 'I-495 HOV', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:i495-n', 'I-495 N', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:i495-near-md', 'I-495 near MD', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:i66-jct', 'I-66', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:i95-hov', 'I-95 HOV', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:jones-branch', 'Jones Branch Dr', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:jones-branch-rt267', 'Jones Branch Dr / Rt 267', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:lee-hwy', 'Lee Hwy', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:route-7', 'Route 7', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:rt-267', 'Rt 267', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:westpark', 'Westpark Dr', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:westpark-b', 'Westpark Dr (B)', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i495x:westpark-c', 'Westpark Dr (C)', 'i495_express');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i66:capital-beltway-begin', 'Capital Beltway Beginning', 'i66_itb');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i66:capital-beltway-end', 'Capital Beltway End', 'i66_itb');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i66:fairfax-dr', 'Fairfax Drive', 'i66_itb');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i66:glebe-rd', 'Glebe Road', 'i66_itb');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i66:lee-highway', 'Lee Highway', 'i66_itb');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i66:leesburg-pike', 'Leesburg Pike', 'i66_itb');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i66:spout-run', 'Spout Run Parkway', 'i66_itb');
INSERT INTO graph_node (node_id, name, corridor) VALUES ('i66:sycamore-st', 'Sycamore Street', 'i66_itb');

-- Edges (341): i95/i495 dynamic (317, keyed od_pair_id), i66 dynamic
-- (20, keyed start_zone_id/end_zone_id), junction connectors (4, feed NULL).
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark-b', 'i495x:i495-n', 'i95', 1000, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-hov', 'i495x:i395-95-495', 'i95', 1001, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-hov', 'i495x:lee-hwy', 'i95', 1002, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-hov', 'i495x:i66-jct', 'i95', 1003, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-hov', 'i495x:route-7', 'i95', 1004, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-hov', 'i495x:westpark', 'i95', 1005, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-hov', 'i495x:jones-branch', 'i95', 1006, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-hov', 'i495x:rt-267', 'i95', 1007, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-hov', 'i495x:i495-n', 'i95', 1008, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:lee-hwy', 'i95', 1009, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:i66-jct', 'i95', 1010, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:route-7', 'i95', 1011, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:westpark', 'i95', 1012, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:jones-branch', 'i95', 1013, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:rt-267', 'i95', 1014, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:i495-n', 'i95', 1015, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:braddock', 'i495x:lee-hwy', 'i95', 1016, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:braddock', 'i495x:i66-jct', 'i95', 1017, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:braddock', 'i495x:route-7', 'i95', 1018, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:braddock', 'i495x:westpark', 'i95', 1019, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:braddock', 'i495x:jones-branch', 'i95', 1020, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:braddock', 'i495x:rt-267', 'i95', 1021, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:braddock', 'i495x:i495-n', 'i95', 1022, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:gallows', 'i495x:lee-hwy', 'i95', 1023, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:gallows', 'i495x:i66-jct', 'i95', 1024, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:gallows', 'i495x:route-7', 'i95', 1025, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:gallows', 'i495x:westpark', 'i95', 1026, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:gallows', 'i495x:jones-branch', 'i95', 1027, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:gallows', 'i495x:rt-267', 'i95', 1028, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:gallows', 'i495x:i495-n', 'i95', 1029, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:route-7', 'i95', 1030, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:westpark', 'i95', 1031, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:jones-branch', 'i95', 1032, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:rt-267', 'i95', 1033, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:i495-n', 'i95', 1034, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:jones-branch', 'i95', 1035, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:rt-267', 'i95', 1036, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:i495-n', 'i95', 1037, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:jones-branch', 'i495x:i495-n', 'i95', 1038, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:i395-495-hov', 'i95', 1039, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:i95-hov', 'i95', 1040, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:i395-95-495', 'i95', 1041, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:braddock', 'i95', 1042, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:gallows', 'i95', 1043, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:i66-jct', 'i95', 1044, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:westpark-b', 'i95', 1045, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:jones-branch-rt267', 'i95', 1046, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:rt-267', 'i495x:i395-495-hov', 'i95', 1047, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:rt-267', 'i495x:i95-hov', 'i95', 1048, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:rt-267', 'i495x:i395-95-495', 'i95', 1049, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:rt-267', 'i495x:braddock', 'i95', 1050, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:rt-267', 'i495x:gallows', 'i95', 1051, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:rt-267', 'i495x:i66-jct', 'i95', 1052, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:rt-267', 'i495x:westpark', 'i95', 1053, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:jones-branch', 'i495x:i395-495-hov', 'i95', 1054, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:jones-branch', 'i495x:i95-hov', 'i95', 1055, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:jones-branch', 'i495x:i395-95-495', 'i95', 1056, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:jones-branch', 'i495x:braddock', 'i95', 1057, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:jones-branch', 'i495x:gallows', 'i95', 1058, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:jones-branch', 'i495x:i66-jct', 'i95', 1059, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:jones-branch', 'i495x:westpark', 'i95', 1060, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:i395-495-hov', 'i95', 1061, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:i95-hov', 'i95', 1062, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:i395-95-495', 'i95', 1063, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:braddock', 'i95', 1064, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:gallows', 'i95', 1065, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:westpark', 'i495x:i66-jct', 'i95', 1066, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:route-7', 'i495x:i395-495-hov', 'i95', 1067, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:route-7', 'i495x:i95-hov', 'i95', 1068, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:route-7', 'i495x:i395-95-495', 'i95', 1069, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:route-7', 'i495x:braddock', 'i95', 1070, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:route-7', 'i495x:gallows', 'i95', 1071, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:route-7', 'i495x:i66-jct', 'i95', 1072, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:i395-495-hov', 'i95', 1073, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:i95-hov', 'i95', 1074, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:i395-95-495', 'i95', 1075, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:braddock', 'i95', 1076, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i495x:gallows', 'i95', 1077, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:lee-hwy', 'i495x:i395-495-hov', 'i95', 1078, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:lee-hwy', 'i495x:i95-hov', 'i95', 1079, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:lee-hwy', 'i495x:i395-95-495', 'i95', 1080, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:lee-hwy', 'i495x:braddock', 'i95', 1081, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:lee-hwy', 'i495x:gallows', 'i95', 1082, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:i395-495-hov', 'i95', 1083, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-95-495', 'i495x:i95-hov', 'i95', 1084, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-hov', 'i495x:i395-95-495', 'i95', 1085, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-hov', 'i495x:lee-hwy', 'i95', 1086, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-hov', 'i495x:i66-jct', 'i95', 1087, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-hov', 'i495x:route-7', 'i95', 1088, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-hov', 'i495x:westpark', 'i95', 1089, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-hov', 'i495x:jones-branch', 'i95', 1090, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-hov', 'i495x:rt-267', 'i95', 1091, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-hov', 'i495x:i495-n', 'i95', 1092, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i495-near-md', 'i495x:westpark-c', 'i95', 1093, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:gordon-blvd', 'i95', 1094, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:fairfax-county-pkwy', 'i95', 1095, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:newington', 'i95', 1096, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:franconia-springfield-pkwy', 'i95', 1097, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:i495-springfield', 'i95', 1098, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:i395-n', 'i95', 1099, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:gordon-blvd', 'i95', 1100, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:fairfax-county-pkwy', 'i95', 1101, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:newington', 'i95', 1102, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:franconia-springfield-pkwy', 'i95', 1103, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:i495-springfield', 'i95', 1104, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:i395-n', 'i95', 1105, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:gordon-blvd', 'i95', 1106, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:fairfax-county-pkwy', 'i95', 1107, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:newington', 'i95', 1108, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:franconia-springfield-pkwy', 'i95', 1109, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:i495-springfield', 'i95', 1110, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:i395-n', 'i95', 1111, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:gordon-blvd', 'i95', 1112, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:fairfax-county-pkwy', 'i95', 1113, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:newington', 'i95', 1114, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:franconia-springfield-pkwy', 'i95', 1115, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:i495-springfield', 'i95', 1116, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:i395-n', 'i95', 1117, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:prince-william-pkwy', 'i95x:fairfax-county-pkwy', 'i95', 1118, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:prince-william-pkwy', 'i95x:newington', 'i95', 1119, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:prince-william-pkwy', 'i95x:franconia-springfield-pkwy', 'i95', 1120, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:prince-william-pkwy', 'i95x:i495-springfield', 'i95', 1121, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:prince-william-pkwy', 'i95x:i395-n', 'i95', 1122, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:gordon-blvd', 'i95x:fairfax-county-pkwy', 'i95', 1123, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:gordon-blvd', 'i95x:newington', 'i95', 1124, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:gordon-blvd', 'i95x:franconia-springfield-pkwy', 'i95', 1125, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:gordon-blvd', 'i95x:i495-springfield', 'i95', 1126, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:gordon-blvd', 'i95x:i395-n', 'i95', 1127, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:us-1', 'i95x:fairfax-county-pkwy', 'i95', 1128, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:us-1', 'i95x:newington', 'i95', 1129, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:us-1', 'i95x:franconia-springfield-pkwy', 'i95', 1130, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:us-1', 'i95x:i495-springfield', 'i95', 1131, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:us-1', 'i95x:i395-n', 'i95', 1132, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:newington', 'i95', 1133, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:franconia-springfield-pkwy', 'i95', 1134, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:i495-springfield', 'i95', 1135, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:i395-n', 'i95', 1136, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:i495-springfield', 'i95', 1140, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:i395-n', 'i95', 1141, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:fairfax-county-pkwy', 'i95x:i495-springfield', 'i95', 1142, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:fairfax-county-pkwy', 'i95x:i395-n', 'i95', 1143, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-rd', 'i95x:i495-springfield', 'i95', 1144, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-rd', 'i95x:i395-n', 'i95', 1145, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:i395-n', 'i95', 1146, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:i495-springfield', 'i95', 1147, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:franconia-rd', 'i95', 1148, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:i95-s-near-backlick-rd', 'i95', 1149, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:franconia-springfield-pkwy', 'i95', 1150, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:us-1', 'i95', 1151, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:gordon-blvd', 'i95', 1152, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:prince-william-pkwy', 'i95', 1153, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:i95-s-near-dale-blvd', 'i95', 1154, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:dumfries', 'i95', 1155, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:joplin-rd', 'i95', 1156, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:garrisonville', 'i95', 1157, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:franconia-rd', 'i95', 1158, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:i95-s-near-backlick-rd', 'i95', 1159, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:franconia-springfield-pkwy', 'i95', 1160, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:us-1', 'i95', 1161, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:gordon-blvd', 'i95', 1162, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:prince-william-pkwy', 'i95', 1163, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:i95-s-near-dale-blvd', 'i95', 1164, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:dumfries', 'i95', 1165, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:joplin-rd', 'i95', 1166, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:garrisonville', 'i95', 1167, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:us-1', 'i95', 1168, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:gordon-blvd', 'i95', 1169, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:prince-william-pkwy', 'i95', 1170, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:i95-s-near-dale-blvd', 'i95', 1171, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:dumfries', 'i95', 1172, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:joplin-rd', 'i95', 1173, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:garrisonville', 'i95', 1174, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:us-1', 'i95', 1175, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:gordon-blvd', 'i95', 1176, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:prince-william-pkwy', 'i95', 1177, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:i95-s-near-dale-blvd', 'i95', 1178, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:dumfries', 'i95', 1179, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:joplin-rd', 'i95', 1180, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:garrisonville', 'i95', 1181, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:us-1', 'i95', 1182, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:gordon-blvd', 'i95', 1183, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:prince-william-pkwy', 'i95', 1184, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:i95-s-near-dale-blvd', 'i95', 1185, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:dumfries', 'i95', 1186, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:joplin-rd', 'i95', 1187, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:garrisonville', 'i95', 1188, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:gordon-blvd', 'i95', 1189, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:prince-william-pkwy', 'i95', 1190, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:i95-s-near-dale-blvd', 'i95', 1191, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:dumfries', 'i95', 1192, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:joplin-rd', 'i95', 1193, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:garrisonville', 'i95', 1194, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:dumfries', 'i95', 1195, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:joplin-rd', 'i95', 1196, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:garrisonville', 'i95', 1197, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dale-blvd', 'i95x:dumfries', 'i95', 1198, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dale-blvd', 'i95x:quantico', 'i95', 1199, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dale-blvd', 'i95x:garrisonville', 'i95', 1200, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:shirlington-circle', 'i95', 1201, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:seminary-rd', 'i95', 1202, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:i395-95', 'i95', 1203, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:i495-springfield', 'i95', 1204, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:franconia-rd', 'i95', 1205, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:i95-s-near-backlick-rd', 'i95', 1206, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:franconia-springfield-pkwy', 'i95', 1207, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:us-1', 'i95', 1208, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:gordon-blvd', 'i95', 1209, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:prince-william-pkwy', 'i95', 1210, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:i95-s-near-dale-blvd', 'i95', 1211, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:dumfries', 'i95', 1212, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:joplin-rd', 'i95', 1213, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:garrisonville', 'i95', 1214, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:i395-95', 'i95', 1215, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:i495-springfield', 'i95', 1216, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:franconia-rd', 'i95', 1217, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:i95-s-near-backlick-rd', 'i95', 1218, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:franconia-springfield-pkwy', 'i95', 1219, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:us-1', 'i95', 1220, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:gordon-blvd', 'i95', 1221, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:prince-william-pkwy', 'i95', 1222, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:i95-s-near-dale-blvd', 'i95', 1223, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:dumfries', 'i95', 1224, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:joplin-rd', 'i95', 1225, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:garrisonville', 'i95', 1226, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:seminary-rd', 'i95', 1227, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:washington-blvd-pentagon', 'i95', 1228, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:washington-dc', 'i95', 1229, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:seminary-rd', 'i95', 1230, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:washington-blvd-pentagon', 'i95', 1231, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:washington-dc', 'i95', 1232, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:seminary-rd', 'i95', 1233, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:washington-blvd-pentagon', 'i95', 1234, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:washington-dc', 'i95', 1235, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:seminary-rd', 'i95', 1236, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:washington-blvd-pentagon', 'i95', 1237, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:washington-dc', 'i95', 1238, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:prince-william-pkwy', 'i95x:seminary-rd', 'i95', 1239, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:prince-william-pkwy', 'i95x:washington-blvd-pentagon', 'i95', 1240, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:prince-william-pkwy', 'i95x:washington-dc', 'i95', 1241, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:gordon-blvd', 'i95x:seminary-rd', 'i95', 1242, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:gordon-blvd', 'i95x:washington-blvd-pentagon', 'i95', 1243, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:gordon-blvd', 'i95x:washington-dc', 'i95', 1244, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:us-1', 'i95x:seminary-rd', 'i95', 1245, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:us-1', 'i95x:washington-blvd-pentagon', 'i95', 1246, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:us-1', 'i95x:washington-dc', 'i95', 1247, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:seminary-rd', 'i95', 1248, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:washington-blvd-pentagon', 'i95', 1249, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:washington-dc', 'i95', 1250, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:seminary-rd', 'i95', 1254, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:washington-blvd-pentagon', 'i95', 1255, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:washington-dc', 'i95', 1256, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:fairfax-county-pkwy', 'i95x:seminary-rd', 'i95', 1257, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:fairfax-county-pkwy', 'i95x:washington-blvd-pentagon', 'i95', 1258, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:fairfax-county-pkwy', 'i95x:washington-dc', 'i95', 1259, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-rd', 'i95x:seminary-rd', 'i95', 1260, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-rd', 'i95x:washington-blvd-pentagon', 'i95', 1261, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-rd', 'i95x:washington-dc', 'i95', 1262, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:seminary-rd', 'i95', 1263, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:washington-blvd-pentagon', 'i95', 1264, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:washington-dc', 'i95', 1265, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i395-n', 'i95x:seminary-rd', 'i95', 1266, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i395-n', 'i95x:washington-blvd-pentagon', 'i95', 1267, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i395-n', 'i95x:washington-dc', 'i95', 1268, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:washington-blvd-pentagon', 'i95', 1269, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:washington-dc', 'i95', 1270, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:shirlington-circle', 'i95x:washington-blvd-pentagon', 'i95', 1271, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:shirlington-circle', 'i95x:washington-dc', 'i95', 1272, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:pentagon', 'i95x:washington-dc', 'i95', 1273, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:gordon-blvd', 'i95', 1274, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:fairfax-county-pkwy', 'i95', 1275, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:newington', 'i95', 1276, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:franconia-springfield-pkwy', 'i95', 1277, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:i495-springfield', 'i95', 1278, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:i395-n', 'i95', 1279, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:seminary-rd', 'i95', 1280, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:washington-blvd-pentagon', 'i95', 1281, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:washington-dc', 'i95', 1282, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:rt17-95-sb', 'i95', 1283, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:rt17-95-sb', 'i95', 1284, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:rt17-95-sb', 'i95', 1285, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:rt17-95-sb', 'i95', 1286, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:rt17-95-sb', 'i95', 1287, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:rt17-95-sb', 'i95', 1288, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:rt17-95-sb', 'i95', 1289, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:rt17-95-sb', 'i95', 1290, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:rt17-95-sb', 'i95', 1291, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:russell-rd', 'i95', 1293, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:russell-rd', 'i95', 1294, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:gordon-blvd', 'i95', 1295, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:fairfax-county-pkwy', 'i95', 1296, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:newington', 'i95', 1297, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:franconia-springfield-pkwy', 'i95', 1298, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:i495-springfield', 'i95', 1299, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:i395-n', 'i95', 1300, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:seminary-rd', 'i95', 1301, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:washington-blvd-pentagon', 'i95', 1302, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:washington-dc', 'i95', 1303, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:russell-rd', 'i95', 1304, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:telegraph-rd', 'i95x:garrisonville', 'i95', 1305, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:telegraph-rd', 'i95x:old-courthouse-rd', 'i95', 1306, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:telegraph-rd', 'i95x:rt17-95-sb', 'i95', 1307, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:opitz', 'i95x:old-courthouse-rd', 'i95', 1310, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:lorton', 'i95x:old-courthouse-rd', 'i95', 1311, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i95-s-ft-belvoir', 'i95x:old-courthouse-rd', 'i95', 1312, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:alban', 'i95x:old-courthouse-rd', 'i95', 1313, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:franconia-springfield-pkwy', 'i95x:old-courthouse-rd', 'i95', 1314, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i95x:old-courthouse-rd', 'i95', 1315, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:turkeycock', 'i95x:old-courthouse-rd', 'i95', 1316, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:seminary-rd', 'i95x:old-courthouse-rd', 'i95', 1317, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dc-pentagon-washington-blvd', 'i95x:old-courthouse-rd', 'i95', 1318, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dale-blvd', 'i95x:old-courthouse-rd', 'i95', 1344, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:dale-blvd', 'i95x:rt17-95-sb', 'i95', 1345, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:rt17-95-nb', 'i95x:opitz', 'i95', 1348, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:old-courthouse-rd', 'i95x:opitz', 'i95', 1349, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:garrisonville', 'i95x:opitz', 'i95', 1350, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:quantico', 'i95x:opitz', 'i95', 1351, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:cardinal', 'i95x:opitz', 'i95', 1352, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:capital-beltway-begin', 'i66:capital-beltway-begin', 'i66', NULL, 3100, 3100);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:capital-beltway-begin', 'i66:lee-highway', 'i66', NULL, 3100, 3110);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:capital-beltway-begin', 'i66:fairfax-dr', 'i66', NULL, 3100, 3120);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:capital-beltway-begin', 'i66:spout-run', 'i66', NULL, 3100, 3130);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:lee-highway', 'i66:lee-highway', 'i66', NULL, 3110, 3110);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:lee-highway', 'i66:fairfax-dr', 'i66', NULL, 3110, 3120);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:lee-highway', 'i66:spout-run', 'i66', NULL, 3110, 3130);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:fairfax-dr', 'i66:fairfax-dr', 'i66', NULL, 3120, 3120);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:fairfax-dr', 'i66:spout-run', 'i66', NULL, 3120, 3130);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:spout-run', 'i66:spout-run', 'i66', NULL, 3130, 3130);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:glebe-rd', 'i66:glebe-rd', 'i66', NULL, 3200, 3200);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:glebe-rd', 'i66:sycamore-st', 'i66', NULL, 3200, 3210);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:glebe-rd', 'i66:leesburg-pike', 'i66', NULL, 3200, 3220);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:glebe-rd', 'i66:capital-beltway-end', 'i66', NULL, 3200, 3230);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:sycamore-st', 'i66:sycamore-st', 'i66', NULL, 3210, 3210);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:sycamore-st', 'i66:leesburg-pike', 'i66', NULL, 3210, 3220);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:sycamore-st', 'i66:capital-beltway-end', 'i66', NULL, 3210, 3230);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:leesburg-pike', 'i66:leesburg-pike', 'i66', NULL, 3220, 3220);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:leesburg-pike', 'i66:capital-beltway-end', 'i66', NULL, 3220, 3230);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:capital-beltway-end', 'i66:capital-beltway-end', 'i66', NULL, 3230, 3230);
-- Springfield express-to-express ramps. NB: i95x trips end at the bare "I-495"
-- node, then continue as the "I-395-95 HOV TO …" 495-NB family (starts TP1NB;
-- the "I-395-95-495" family is GP entry at TP2NB, not this movement). SB: 495
-- trips ending "TO I-95 HOV" (south) or "TO I-395-495 HOV" (north, reversible)
-- both continue as i95-corridor trips from the bare "I-495" origin.
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i95x:i495-springfield', 'i495x:i395-95-hov', NULL, NULL, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i95-hov', 'i95x:i495-springfield', NULL, NULL, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i395-495-hov', 'i95x:i495-springfield', NULL, NULL, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i495x:i66-jct', 'i66:capital-beltway-begin', NULL, NULL, NULL, NULL);
INSERT INTO graph_edge (from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id) VALUES ('i66:capital-beltway-end', 'i495x:i66-jct', NULL, NULL, NULL, NULL);

COMMIT;
