#!/usr/bin/env python3
"""Generate directional Graphviz DOT files for the toll graph's connectivity.

Reads db/graph.sql (the seed source of truth) and emits two digraphs into
docs/:

  graph-connectivity-northbound.dot   -- every south->north express edge
  graph-connectivity-southbound.dot   -- every north->south express edge

I-495 and I-66 are always-open (not reversible), so I-66's 20 zone edges and
the 5 free junction connectors appear in BOTH files; only the reversible
I-95/395 + I-495 express OD pairs split by direction. All 60 nodes appear in
both files, including "no-exit" sinks (no outgoing edge in that direction).

Render:  dot -Tsvg docs/graph-connectivity-northbound.dot -o nb.svg

graph.sql carries no coordinates, so the north->south ordering below is the
same curated order used by the audit/overview docs. Keep it in sync if the
seed's node set ever changes.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SQL = (REPO / "db" / "graph.sql").read_text()

# North-first geographic order (index 0 = northernmost). Only i95/i495 need an
# order; i66 is east-west and always-open so it isn't direction-split.
I95_ORDER = [
    "i95x:washington-dc", "i95x:dc-pentagon-washington-blvd", "i95x:pentagon",
    "i95x:washington-blvd-pentagon", "i95x:shirlington-circle", "i95x:seminary-rd",
    "i95x:i395-n", "i95x:i395-95", "i95x:telegraph-rd", "i95x:i495-springfield",
    "i95x:i95-s-near-backlick-rd", "i95x:turkeycock", "i95x:franconia-rd",
    "i95x:franconia-springfield-pkwy", "i95x:i95-s-ft-belvoir", "i95x:alban",
    "i95x:lorton", "i95x:newington", "i95x:fairfax-county-pkwy", "i95x:us-1",
    "i95x:prince-william-pkwy", "i95x:gordon-blvd", "i95x:opitz", "i95x:cardinal",
    "i95x:i95-s-near-dale-blvd", "i95x:dale-blvd", "i95x:dumfries", "i95x:joplin-rd",
    "i95x:russell-rd", "i95x:quantico", "i95x:old-courthouse-rd", "i95x:rt17-95-sb",
    "i95x:rt17-95-nb", "i95x:garrisonville",
]
I495_ORDER = [
    "i495x:i495-near-md", "i495x:i495-n", "i495x:lee-hwy", "i495x:jones-branch-rt267",
    "i495x:jones-branch", "i495x:westpark-c", "i495x:westpark-b", "i495x:westpark",
    "i495x:rt-267", "i495x:route-7", "i495x:i66-jct", "i495x:gallows", "i495x:braddock",
    "i495x:i495-hov", "i495x:i395-495-hov", "i495x:i95-hov", "i495x:i395-95-hov",
    "i495x:i395-95-495",
]
ORDER = {n: i for i, n in enumerate(I95_ORDER)}
ORDER.update({n: i for i, n in enumerate(I495_ORDER)})

CORRIDOR_STYLE = {
    "i95_express": ("#2f6fe0", "#eaf1fc", "I-95 / 395 Express"),
    "i495_express": ("#12996a", "#e6f6ef", "I-495 Beltway Express"),
    "i66_itb": ("#c9761a", "#fbf0e2", "I-66 Inside the Beltway"),
}


def parse():
    nodes = {}
    for nid, name, corr in re.findall(
        r"graph_node \(node_id, name, corridor\) VALUES \('([^']+)', '([^']*)', '([^']+)'\)",
        SQL,
    ):
        nodes[nid] = {"name": name, "corridor": corr}
    edges = []
    for f, t, feed in re.findall(
        r"graph_edge \(from_node, to_node, feed, od_pair_id, start_zone_id, end_zone_id\) "
        r"VALUES \('([^']+)', '([^']+)', (NULL|'i95'|'i66'), (?:NULL|\d+), (?:NULL|\d+), (?:NULL|\d+)\)",
        SQL,
    ):
        edges.append((f, t, feed.strip("'") if feed != "NULL" else None))
    return nodes, edges


def corr_of(nid):
    return "i66" if nid.startswith("i66:") else ("i495" if nid.startswith("i495x:") else "i95")


def direction(f, t):
    """'NB', 'SB', or 'both' (always-open i66 / cross-corridor connectors)."""
    cf, ct = corr_of(f), corr_of(t)
    if cf != ct:          # free junction connector between corridors
        return "both"
    if cf == "i66":       # east-west, always open, not reversible
        return "both"
    return "NB" if ORDER[t] < ORDER[f] else "SB"


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit(direction_tag, nodes, edges):
    want = {direction_tag, "both"}
    active = [(f, t, fd) for f, t, fd in edges if direction(f, t) in want]
    outdeg = {n: 0 for n in nodes}
    indeg = {n: 0 for n in nodes}
    for f, t, _ in active:
        outdeg[f] += 1
        indeg[t] += 1

    full = "Northbound" if direction_tag == "NB" else "Southbound"
    lines = [
        f"// {full} connectivity of the NOVA toll graph -- GENERATED by",
        "// scripts/gen_graph_dot.py from db/graph.sql. Do not hand-edit.",
        f"// {len(nodes)} nodes, {len(active)} active edges "
        f"(i95/i495 {full.lower()} + always-open i66 + connectors).",
        "digraph toll_" + direction_tag.lower() + " {",
        "  rankdir=TB;",
        "  graph [splines=curved, nodesep=0.28, ranksep=0.7, fontname=\"Helvetica\", "
        f'label="NOVA toll graph -- {full} traversal  (double border = no outgoing '
        'edge in this direction)", labelloc=t, fontsize=20];',
        '  node [shape=box, style="rounded,filled", fontname="Courier", fontsize=10];',
        '  edge [color="#8894a5", arrowsize=0.7, penwidth=0.8];',
        "",
    ]

    # nodes grouped into corridor clusters
    by_corr = {}
    for nid, meta in nodes.items():
        by_corr.setdefault(meta["corridor"], []).append(nid)
    for corr, ids in by_corr.items():
        border, fill, title = CORRIDOR_STYLE[corr]
        lines.append(f"  subgraph cluster_{corr} {{")
        lines.append(f'    label="{title}"; color="{border}"; fontcolor="{border}"; '
                     'style=rounded; fontname="Helvetica-Bold";')
        for nid in ids:
            name = nodes[nid]["name"]
            peris = 2 if outdeg[nid] == 0 else 1        # sink = no outgoing edge here
            pen = 2.4 if indeg[nid] == 0 else 1.0        # source = no incoming edge here
            lines.append(
                f'    "{nid}" [label="{esc(nid)}\\n{esc(name)}", color="{border}", '
                f'fillcolor="{fill}", peripheries={peris}, penwidth={pen}];'
            )
        lines.append("  }")
        lines.append("")

    # edges, colored by the origin's corridor; connectors dashed
    for f, t, fd in active:
        if fd is None:
            lines.append(f'  "{f}" -> "{t}" [style=dashed, color="#b0b8c2", '
                         'label="free", fontsize=8, fontcolor="#8894a5"];')
        else:
            border = CORRIDOR_STYLE[nodes[f]["corridor"]][0]
            lines.append(f'  "{f}" -> "{t}" [color="{border}99"];')

    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    nodes, edges = parse()
    out = {
        "NB": REPO / "docs" / "graph-connectivity-northbound.dot",
        "SB": REPO / "docs" / "graph-connectivity-southbound.dot",
    }
    for tag, path in out.items():
        path.write_text(emit(tag, nodes, edges))
        active = sum(1 for f, t, fd in edges if direction(f, t) in {tag, "both"})
        print(f"wrote {path.relative_to(REPO)}  ({len(nodes)} nodes, {active} edges)")


if __name__ == "__main__":
    sys.exit(main())
