"""dulles_route: resolve a human trip between two interchanges on the Dulles
Toll Road and/or the Dulles Greenway to its route and its price.

Both facilities are fixed-toll roads (no dynamic pricing, no price history),
so unlike i66_route/i95_route this tool never touches RDS -- pricing lives
directly in the committed oracles (oracles/dulles_toll_road.json,
oracles/dulles_greenway.json), regenerated by
scripts/build_dulles_oracle.py. See that script's docstring for sourcing and
the three documented v1 assumptions (Exit 16's EB-only ramp toll, weekday-only
peak windows, 2-axle E-ZPass rates only).

Route resolution is a flat lookup against each facility's own committed
pairs, same principle as i66_route: "where an oracle exists, prefer reading
it over re-deriving it." A trip confined to one facility is a single-leg
lookup exactly like i66. A trip crossing both facilities (Dulles Toll Road
and Dulles Greenway are one continuous physical corridor, connected at
Route 28) resolves as two legs -- origin to the Route 28 boundary on one
facility, boundary to destination on the other -- summed into one total.
(i95_route/i495_route dropped this same composite-and-sum shape for their
own cross-corridor case, in favor of not resolving a cross-corridor trip
at all -- see docs/oracle-findings.md section 8. Not synced here: Dulles's
two facilities are few enough and stable enough (two operators, one
crossing point) that the tradeoffs that motivated dropping it for
i95/i495 -- 16 unpriced od_pair_ids, a live-fallback source, per-leg
facility classification -- don't apply the same way.) Real-world billing
matches the two-separate-tolls model this produces: "vehicles traversing
both roads incur separate toll charges" (the two operators bill
independently, never combined into one flat fare) -- summing them into a
convenience total is this tool's own addition, not a claim Dulles bills
one combined toll.

`at_time` still exists here, unlike a first pass at this tool assumed it
wouldn't -- the Dulles Toll Road has no time-of-day pricing, but the Dulles
Greenway does (peak vs off-peak, weekdays only), so at_time is needed to
classify Greenway legs. It plays no role in route resolution, same as
i66/i95's at_time.

See docs/oracle-tools-spec.md for the full contract.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, time
from decimal import Decimal
from pathlib import Path
from zoneinfo import ZoneInfo

from strands import tool

logger = logging.getLogger(__name__)

# ponytail: path assumes agent_tools/ sits one level under the repo root next
# to oracles/, matching i66_route.py/i95_route.py's existing assumption.
_ORACLE_DIR = Path(__file__).resolve().parent.parent / "oracles"
_EASTERN = ZoneInfo("America/New_York")
_BOUNDARY_LABEL = "Route 28 (Dulles Toll Road / Dulles Greenway)"


def _load_facility(filename: str) -> dict:
    oracle = json.loads((_ORACLE_DIR / filename).read_text())
    nodes = oracle["nodes"]
    label_index: dict[str, list[str]] = {}
    for node_id, node in nodes.items():
        label_index.setdefault(node["label"].casefold(), []).append(node_id)
    boundary_id = next(
        node_id for node_id, node in nodes.items() if node["label"] == _BOUNDARY_LABEL
    )
    return {
        "nodes": nodes,
        "pairs": oracle["pairs"],
        "label_index": label_index,
        "boundary_id": boundary_id,
    }


_FACILITIES = {
    "dulles_toll_road": _load_facility("dulles_toll_road.json"),
    "dulles_greenway": _load_facility("dulles_greenway.json"),
}

# Peak applies weekdays only (Mon-Fri); see build script docstring for why
# this is a documented assumption, not a quoted fact.
_GREENWAY_PEAK_WINDOWS = {
    "EB": (time(6, 30), time(9, 0)),
    "WB": (time(16, 0), time(18, 30)),
}


def _resolve_in_facility(facility: dict, query: str) -> list[str]:
    if query in facility["nodes"]:
        return [query]
    return facility["label_index"].get(query.casefold(), [])


def _direct_pairs(
    facility: dict, origin_ids: list[str], destination_ids: list[str]
) -> list[dict]:
    return [
        p
        for p in facility["pairs"]
        if p["entry"] in origin_ids and p["exit"] in destination_ids
    ]


def _entry_capable_labels(facility: dict) -> set[str]:
    return {facility["nodes"][p["entry"]]["label"] for p in facility["pairs"]}


def _exit_capable_labels(facility: dict) -> set[str]:
    return {facility["nodes"][p["exit"]]["label"] for p in facility["pairs"]}


# ponytail: resolution/matching pattern duplicated with i66_route.py/i95_route.py's
# _lookup; extract if a fourth oracle-backed tool needs the same shape.
def _lookup(origin: str, destination: str) -> dict:
    origin_ids = {
        name: _resolve_in_facility(f, origin) for name, f in _FACILITIES.items()
    }
    destination_ids = {
        name: _resolve_in_facility(f, destination) for name, f in _FACILITIES.items()
    }

    if not any(origin_ids.values()):
        valid = sorted(
            {label for f in _FACILITIES.values() for label in _entry_capable_labels(f)}
        )
        return {
            "error": f"unknown origin {origin!r}: no matching label or node id on either facility",
            "valid_options": valid,
        }
    if not any(destination_ids.values()):
        valid = sorted(
            {label for f in _FACILITIES.values() for label in _exit_capable_labels(f)}
        )
        return {
            "error": f"unknown destination {destination!r}: no matching label or node id on either facility",
            "valid_options": valid,
        }

    single_leg = [
        (name, p)
        for name, facility in _FACILITIES.items()
        if origin_ids[name] and destination_ids[name]
        for p in _direct_pairs(facility, origin_ids[name], destination_ids[name])
    ]
    if len(single_leg) == 1:
        name, pair = single_leg[0]
        return {"legs": [(name, pair)]}
    if len(single_leg) > 1:
        return {
            "error": f"ambiguous trip: {origin!r} to {destination!r} matches {len(single_leg)} entry/exit combinations",
            "valid_options": sorted(
                {p["entry"] for _, p in single_leg} | {p["exit"] for _, p in single_leg}
            ),
        }

    composite = _composite_lookup(origin_ids, destination_ids)
    if composite is not None:
        return {"legs": composite}

    reachable = sorted(
        {
            facility["nodes"][p["exit"]]["label"]
            for name, facility in _FACILITIES.items()
            for p in _direct_pairs(facility, origin_ids[name], list(facility["nodes"]))
        }
    )
    return {
        "error": f"no direct or connecting trip from {origin!r} to {destination!r}",
        "valid_options": reachable,
    }


def _composite_lookup(
    origin_ids: dict[str, list[str]], destination_ids: dict[str, list[str]]
) -> list[tuple[str, dict]] | None:
    """A trip starting on one facility and ending on the other, split at the
    Route 28 boundary each oracle shares. Returns None if either leg doesn't
    resolve to exactly one pair (real data always does -- the boundary node
    is a valid entry/exit almost everywhere on both facilities).
    """
    names = list(_FACILITIES)
    for a, b in ((names[0], names[1]), (names[1], names[0])):
        if not origin_ids[a] or not destination_ids[b]:
            continue
        facility_a, facility_b = _FACILITIES[a], _FACILITIES[b]
        leg1 = _direct_pairs(facility_a, origin_ids[a], [facility_a["boundary_id"]])
        leg2 = _direct_pairs(
            facility_b, [facility_b["boundary_id"]], destination_ids[b]
        )
        if len(leg1) == 1 and len(leg2) == 1:
            return [(a, leg1[0]), (b, leg2[0])]
    return None


def _resolve_at_time(at_time: str | None, *, now=None) -> datetime:
    """Parse the caller's at_time, defaulting to now (America/New_York).

    Identical semantics to i66_route._resolve_at_time/i95_route._resolve_at_time
    -- kept as a separate copy per this repo's existing duplication convention
    for these small oracle-backed tools, not shared, since dulles_route uses
    it only to classify Greenway peak/off-peak, never to pick a historical row.
    """
    if at_time is None:
        return (now or (lambda: datetime.now(_EASTERN)))()
    dt = datetime.fromisoformat(at_time)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=_EASTERN)
    return dt


def _is_greenway_peak(at_time: datetime, direction: str) -> bool:
    # Peak windows are Eastern wall-clock time; convert first so a caller
    # passing an explicit non-Eastern offset is classified correctly.
    local = at_time.astimezone(_EASTERN)
    if local.weekday() >= 5:  # Saturday/Sunday
        return False
    start, end = _GREENWAY_PEAK_WINDOWS[direction]
    return start <= local.time() < end


def _price_leg(facility_name: str, pair: dict, at_time: datetime) -> dict:
    nodes = _FACILITIES[facility_name]["nodes"]
    entry_id, exit_id = pair["entry"], pair["exit"]
    if facility_name == "dulles_greenway":
        peak = _is_greenway_peak(at_time, pair["direction"])
        rate_period = "peak" if peak else "off_peak"
    else:
        rate_period = None  # Dulles Toll Road has no time-of-day pricing
    price = (
        pair["price_peak_usd"] if rate_period == "peak" else pair["price_off_peak_usd"]
    )
    return {
        "facility": facility_name,
        "direction": pair["direction"],
        "entry": {"node_id": entry_id, "label": nodes[entry_id]["label"]},
        "exit": {"node_id": exit_id, "label": nodes[exit_id]["label"]},
        "price_usd": price,
        "rate_period": rate_period,
    }


def _build_response(
    origin: str, destination: str, legs: list[dict], at_time: datetime
) -> dict:
    facility_totals = {name: Decimal("0.00") for name in _FACILITIES}
    for leg in legs:
        facility_totals[leg["facility"]] += Decimal(leg["price_usd"])
    total = sum(facility_totals.values(), Decimal("0"))
    return {
        "origin": origin,
        "destination": destination,
        "at_time": at_time.isoformat(),
        "legs": legs,
        "facility_totals": {name: str(v) for name, v in facility_totals.items()},
        "total_usd": str(total),
    }


@tool
def dulles_route(origin: str, destination: str, at_time: str | None = None) -> dict:
    """Resolve a trip on the Dulles Toll Road and/or Dulles Greenway to its route and price.

    Looks up origin/destination against the two committed oracles
    (oracles/dulles_toll_road.json, oracles/dulles_greenway.json) -- a flat,
    direct lookup, never multi-hop routing. A trip confined to one facility
    resolves to one leg; a trip crossing both (they connect at Route 28)
    resolves to two legs, split at that boundary and summed, since the two
    operators bill independently.

    Args:
        origin: Interchange label (e.g. 'Exit 12 - SR 602 (Reston Pkwy)'),
            case-insensitive, or the oracle's raw node id (e.g. '12') as a
            fallback.
        destination: Same rules as origin.
        at_time: ISO-8601 timestamp; a value with no offset is assumed
            America/New_York. Defaults to now (America/New_York) if omitted.
            The Dulles Toll Road has no time-of-day pricing; the Dulles
            Greenway does (peak: weekdays 6:30-9:00am eastbound, 4:00-6:30pm
            westbound), so at_time only affects Greenway legs, via each
            leg's rate_period.

    Returns:
        dict: On success, {"origin", "destination", "at_time",
        "legs": [{"facility": "dulles_toll_road"|"dulles_greenway",
        "direction", "entry": {"node_id", "label"}, "exit": {"node_id",
        "label"}, "price_usd": str, "rate_period": "peak"|"off_peak"|None},
        ...], "facility_totals": {"dulles_toll_road": str,
        "dulles_greenway": str}, "total_usd": str} -- one leg for a
        single-facility trip, two for a trip crossing both. price_usd/
        total_usd/facility_totals values are decimal strings, never float.
        rate_period is None for Dulles Toll Road legs (no time-of-day
        pricing there). On failure, {"error": str, "valid_options":
        [str, ...]} -- the combined entry/exit-capable label list across
        both facilities on an unknown identifier, the labels reachable from
        a known origin on no direct or connecting trip, or a malformed
        at_time (valid_options empty, since retrying won't fix it).
    """
    result = _lookup(origin, destination)
    if "error" in result:
        logger.info(
            "dulles_route miss origin=%r destination=%r error=%r",
            origin,
            destination,
            result["error"],
        )
        return result

    try:
        resolved_at_time = _resolve_at_time(at_time)
    except ValueError as e:
        error = {"error": f"invalid at_time {at_time!r}: {e}", "valid_options": []}
        logger.info(
            "dulles_route miss origin=%r destination=%r error=%r",
            origin,
            destination,
            error["error"],
        )
        return error

    legs = [_price_leg(name, pair, resolved_at_time) for name, pair in result["legs"]]
    response = _build_response(origin, destination, legs, resolved_at_time)
    logger.info(
        "dulles_route ok origin=%r destination=%r at_time=%s total_usd=%s legs=%s",
        origin,
        destination,
        response["at_time"],
        response["total_usd"],
        response["legs"],
    )
    return response
